export const titleMap = {
  '/': '首页 - 佩蒂官网网站',
  '/pages/corporate-philosophy': '企业理念 - 佩蒂官网网站',
  '/pages/company-culture': '企业文化 - 佩蒂官网网站',
  '/pages/development-path': '发展历程 - 佩蒂官网网站',
  '/pages/group-structure': '集团架构 - 佩蒂官网网站',
  '/pages/production-base': '生产基地 - 佩蒂官网网站',
  '/pages/production-capacity': '生产能力 - 佩蒂官网网站',
  '/pages/research-capabilities': '研发能力 - 佩蒂官网网站',
  '/pages/quality-control': '质量管理 - 佩蒂官网网站',
  '/pages/order-process': '订单流程 - 佩蒂官网网站',
  '/pages/product-center': '产品中心 - 佩蒂官网网站',
  '/collection/meatyway': '爵宴 - 佩蒂官网网站',
  '/collection/health': '好适嘉 - 佩蒂官网网站',
  '/collection/chewnergy': '齿能 - 佩蒂官网网站',
  '/collection/smartbones': 'SmartBones - 佩蒂官网网站',
  '/blogs/news': '企业新闻 - 佩蒂官网网站',
  '/blogs/video': '视频 - 佩蒂官网网站',
  '/contact-us': '联系我们 - 佩蒂官网网站',
};